openapi: "3.0.0"
info:
  version: 1.0.0
  title: eDCR as service
  description: Service to scrutinize plan in dxf file format and generate report. Use the transaction number to track the status/retrieve saved information.
  contact:
    name: Egovernments Foundation
    email: contact@egovernments.org
servers:
- url: https://digit-bpa-dev-jupiter.egovernments.org/eDcr
  description: Development server
paths:
  /rest/dcr/scrutinizeplan:
    post:
      summary: Scrutinize dxf file scrutiny.
      requestBody:
        content:
          multipart/mixed:
            schema:
              $ref: '#/components/schemas/ScrutinizePlanReq'
            encoding:
              dxfFile:
              # only accept dxf file.
                contentType: application/dxf
      responses:
        '200':
          description: scrutinize plan successful.
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/ScrutinizePlanResponse'
              encoding:
                dxfFile:
                # only accept dxf file.
                  contentType: application/dxf
                planPdfs:
                  contentType: application/pdf
                planReport:
                  contentType: application/pdf   
        '400':
          description: Invalid Input
          content:
            application/json:
              schema:
                 $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
      tags:
        - Scrutinize Plan

  /rest/dcr/scrutinydetails:
    post:
      summary: Get plan detail object by passing transaction number or edcr number.
      requestBody:
        description: Get the scrutinized plan and detail by passing transaction number or edcr number.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScrutinizePlanSearchReq'  
      parameters:
        - name: tenantId
          in: query
          description: city name
          required: true
          schema:
           type: string
        - name: edcrNumber
          in: query
          description: edcr Number 
          required: false
          schema:
           type: string
        - name: transactionNumber
          in: query
          description: transaction Number 
          required: true
          schema:
           type: string
      responses:
        '200':
          description: successful return of details if exist
          content:
            application/json:
              schema:
                type: array
                items:
                   $ref: '#/components/schemas/ScrutinizePlanResponse'
              encoding:
                dxfFile:
                # only accept dxf file.
                  contentType: application/dxf
                planPdfs:
                  contentType: application/pdf
                planReport:
                  contentType: application/pdf     
      tags:
        - View Scrutiny Details

components:
  schemas:
    EdcrDetail:
      type: object
      description: EncrReqObject contains data to be encrypted and meta-data required to perform the encryption.
      properties:
        transactionNumber:
          type: string
          description: Unique Transaction Number for each request.
        planDetail:
          type: string
          description: Dxf file content in object format
        edcrNumber:
          type: string
          description: If application approved, dcr number will be generated
        planPdfs:
          type:  array
          items:
            type: string
            format: binary 
            description: Auto generated pdfs
        dxfFile:
            type: string
            format: binary  
            description: Scrutinizeed dxf file
            maximum: 23333
        updatedDxfFile:
            type: string
            format: binary  
            description: Scrutinizeed dxf file
            maximum: 23333
        planReport:
            type: string
            format: binary  
            description: Generated report 
        status:
            type: string
            description: Status of the application
            enum:
              - Approved
              - Rejected
        tenantId:
          # Rules scrutiny based on tenant id.
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/tenantId'
    ScrutinizePlanSearchReq:
      type: object
      description: ScrutinizePlanSearchReq contains data to be search as plan
      properties:
        requestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
      required:
         -  requestInfo
    ScrutinizePlanReq:
      type: object
      description: ScrutinizePlanReq contains data to be submit as plan
      properties:
        tenantId:
          # Rules scrutiny based on tenant id.
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/tenantId'
        transactionNumber:
          type: string
          description: Unique Transaction Number for each request.
        requestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
        dxfFile:
            type: string
            format: binary  
            description: Scrutinized dxf file
      example:
          tenantId: "sonpur"
          transactionNumber: "1"
          requestInfo: {
          }
          dxfFile:  ""
      required:
         -  tenantId
         -  transactionNumber
         -  dxfFile
    ScrutinizePlanResponse:
      description: Contract class for web response. Array of ScrutinizePlan items  are used in case of search.
      properties:
        responseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
        edcrDetail:
          description: Used for search result and create only
          type:  array
          items:
            $ref: '#/components/schemas/EdcrDetail'
