openapi: 3.0.0
info:
  version: 1.0.0
  title: eDCR as service
  description: Service to scrutinize plan in dxf file format and generate report. Use the transaction number to track the status/retrieve saved information.
  contact:
    name: Egovernments Foundation
    email: contact@egovernments.org
servers:
  - url: https://egov-dcr-galaxy.egovernments.org/edcr
    description: Development server
    
paths:
  /rest/dcr/scrutinizeplan:
    post:
      summary: This API will scrutinize the building plan drawing(dxf) file send along and gives the plan scrutiny result as response along with a unique eDCR number on successful processing.
      requestBody:
        content:
          multipart/mixed:
            schema:
              $ref: '#/components/schemas/ScrutinizePlanReq'
            encoding:
              dxfFile:
                contentType: application/dxf
      responses:
        '200':
          description: Plan scrutanized successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScrutinizePlanResponse'
              encoding:
                dxfFile:
                  contentType: application/dxf
                planPdfs:
                  contentType: application/pdf
                planReport:
                  contentType: application/pdf
        '400':
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
      tags:
        - Scrutinize Plan
        
  /rest/dcr/scrutinydetails:
    post:
      summary:  This API is used to fetch the details of the plan that is already scrutinized in the system by providing a transaction number or a eDCR number.
      requestBody:
        description: Send the unique transaction number that was used for plan scrutiny or the system generated eDCR number that was received as part of the scrutiny response for getting the details of scrutiny.
        content:
          application/json:
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
      parameters:
        - name: tenantId
          in: query
          description: Unique identifier of the city/state for which the record belong to.
          required: true
          schema:
            type: string
        - name: edcrNumber
          in: query
          description: edcr Number that was generated by the system as part of plan scrutiny.
          required: false
          schema:
            type: string
        - name: transactionNumber
          in: query
          description: Transaction Number number that was orignially sent to the system along with the drawing for scrutiny.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successfully list the details of the plan scrutiny if the system can identify the plan as per the details send. In case where system does not find the scrutiny details based on the input send, it will send a message back as "Invalid Input- Record not found".
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScrutinizePlanResponse'
              encoding:
                dxfFile:
                  contentType: application/dxf
                planPdfs:
                  contentType: application/pdf
                planReport:
                  contentType: application/pdf
      tags:
        - Search Scrutiny Details
        
components:
  schemas:
    EdcrDetail:
      type: object
      description: EncrReqObject contains data to be encrypted and meta-data required to perform the encryption.
      properties:
        transactionNumber:
          type: string
          maxLength: 32
          description: Unique Transaction Number for each request.
        planDetail:
          type: string
          description: Dxf file content in object format
        edcrNumber:
          type: string
          maxLength: 32
          description: If the plan is approved, eDCR number will be generated by the system.
        planPdfs:
          type: array
          items:
            type: string
            format: url 
            description: System generated pdfs of the drawings(dxf) uploaded.
        dxfFile:
          type: string
          format: url
          description: Plan drawing file that is scrutinized which is of .dxf extension.
          maximum: 23333
        updatedDxfFile:
          type: string
          format: url
          description: System upgraded version of the uploaded dxf file.
          maximum: 23333
        planReport:
          type: string
          format: url
          description: System generated scrutiny report for the uploaded drawing(dxf). This will be a pdf file 
        status:
          type: string
          description: Status of the plan after the scrutiny process. If all the rules are passed the status will be "Approved". If one of the rules is failed the status will be "Rejected".
          enum:
            - Accepted
            - Not Accepted
        tenantId:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/tenantId'

    ScrutinizePlanReq:
      type: object
      description: This object contains data to be submitted for scrutanizing a plan drawing.
      properties:
        tenantId:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/tenantId'
        transactionNumber:
          type: string
          maxLength: 32
          description: Unique Transaction Number for each request.
        requestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
        dxfFile:
          type: string
          x-mimetype: application/dxf
          description: The builing plan drawing file, in .dxf format, which needs to be scrutinized.
      example:
        tenantId: sonpur
        transactionNumber: '1'
        requestInfo: {}
        dxfFile: ''
      required:
        - tenantId
        - transactionNumber
        - dxfFile
        
    ScrutinizePlanResponse:
      description: This object contains the response of a file scrutiny along with all the reports and status. 
      properties:
        responseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
        edcrDetail:
          description: Used for search result and create only
          type: array
          items:
            $ref: '#/components/schemas/EdcrDetail'