openapi: 3.0.0
info:
  version: 1.0.0
  title: eDCR as service
  description: Service to scrutinize plan in dxf file format and generate report. Use the transaction number to track the status/retrieve saved information.
  contact:
    name: Egovernments Foundation
    email: contact@egovernments.org
servers:
  - url: https://egov-dcr-galaxy.egovernments.org/edcr
    description: Development server
    
paths:
  /rest/dcr/scrutinizeplan:
    post:
      summary: This API will scrutinize the building plan drawing(dxf) file send along and gives the plan scrutiny result as response along with a unique eDCR number on successful processing.
      requestBody:
        content:
          multipart/mixed:
            schema:
              $ref: '#/components/schemas/ScrutinizePlanReq'
            encoding:
              dxfFile:
                contentType: application/dxf
      responses:
        '200':
          description: Plan scrutanized successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScrutinizePlanResponse'
              encoding:
                dxfFile:
                  contentType: application/dxf
                planPdfs:
                  contentType: application/pdf
                planReport:
                  contentType: application/pdf
        '400':
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
      tags:
        - Scrutinize Plan
        
  /rest/dcr/scrutinydetails:
    post:
      summary:  This API is used to fetch the details of the plan that is already scrutinized in the system by providing a transaction number or a eDCR number.
      requestBody:
        description: Send the unique transaction number that was used for plan scrutiny or the system generated eDCR number that was received as part of the scrutiny response for getting the details of scrutiny.
        content:
          application/json:
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
      parameters:
        - name: tenantId
          in: query
          description: Unique identifier of the city/state for which the record belong to.
          required: true
          schema:
            type: string
        - name: edcrNumber
          in: query
          description: edcr Number that was generated by the system as part of plan scrutiny.
          required: false
          schema:
            type: string
        - name: transactionNumber
          in: query
          description: Transaction Number number that was orignially sent to the system along with the drawing for scrutiny.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Successfully list the details of the plan scrutiny if the system can identify the plan as per the details send. In case where system does not find the scrutiny details based on the input send, it will send a message back as "Invalid Input- Record not found".
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScrutinizePlanResponse'
              encoding:
                dxfFile:
                  contentType: application/dxf
                planPdfs:
                  contentType: application/pdf
                planReport:
                  contentType: application/pdf
      tags:
        - Search Scrutiny Details
        
  /edcr/oauth/token:
    post:
      summary: To access the Secured RESTful APIs, Access token is required. Use this API to get the access token which is valid for 30 mins. 
      requestBody:
        description: By passing username and password auth generate oAuth token.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthTokenRequest'  
      parameters:
        - name: tenantId
          in: query
          description: city name
          required: true
          schema:
           type: string
        - name: userName
          in: header
          required: true
          description: Client User Name provided by erp for each client to generate authtoken
          schema:
            type: string
        - name: password
          in: header
          required: true
          description: Client Password provided by erp for each client to generate authtoken
          schema:
            type: string
            format: password
      responses:
        '200':
          description: Authtoken generated in case of valid user details.
          content:
            application/json:
              schema:
                   $ref: '#/components/schemas/AuthTokenResponse'
      tags:
        - Get Access Token      
        
components:
  schemas:
    EdcrDetail:
      type: object
      description: EncrReqObject contains data to be encrypted and meta-data required to perform the encryption.
      properties:
        transactionNumber:
          type: string
          description: Unique Transaction Number for each request.
        planDetail:
          type: string
          description: Dxf file content in object format
        edcrNumber:
          type: string
          description: If the plan is approved, eDCR number will be generated by the system.
        planPdfs:
          type: array
          items:
            type: string
            format: binary
            description: System generated pdfs of the drawings(dxf) uploaded.
        dxfFile:
          type: string
          format: binary
          description: Plan drawing file that is scrutinized which is of .dxf extension.
          maximum: 23333
        updatedDxfFile:
          type: string
          format: binary
          description: System upgraded version of the uploaded dxf file.
          maximum: 23333
        planReport:
          type: string
          format: binary
          description: System generated scrutiny report for the uploaded drawing(dxf). This will be a pdf file 
        status:
          type: string
          description: Status of the plan after the scrutiny process. If all the rules are passed the status will be "Approved". If one of the rules is failed the status will be "Rejected".
          enum:
            - Approved
            - Rejected
        tenantId:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/tenantId'

    ScrutinizePlanReq:
      type: object
      description: This object contains data to be submitted for scrutanizing a plan drawing.
      properties:
        tenantId:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/tenantId'
        transactionNumber:
          type: string
          description: Unique Transaction Number for each request.
        requestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
        dxfFile:
          type: string
          format: binary
          description: The builing plan drawing file, in .dxf format, which needs to be scrutanized.
      example:
        tenantId: sonpur
        transactionNumber: '1'
        requestInfo: {}
        dxfFile: ''
      required:
        - tenantId
        - transactionNumber
        - dxfFile
        
    ScrutinizePlanResponse:
      description: This object contains the response of a file scrutiny along with all the reports and status. 
      properties:
        responseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
        edcrDetail:
          description: Used for search result and create only
          type: array
          items:
            $ref: '#/components/schemas/EdcrDetail'
    
    AuthTokenRequest:
      type: object
      description: Pass the username and password created/provided by erp system to access the secured rest api's.
      properties:
        grant_type:
          type: string
          description: Pass "password" as default value. 
        username:
          type: string
          description: Unique application user name provided by erp system.
        password:
            type: string
            description: The password of the application user name provided by erp system.
      example:
          grant_type: "password"
          username: "username"
          password: "password"
      required:
         -  grant_type
         -  username
         -  password
    AuthTokenResponse:
      type: object
      description: The access token is given by the authorization server when it accepts the client ID and client password sent by the client application.
      properties:
        access_token:
          type: string
          description: The access token string as issued by the authorization server.
        token_type:
          type: string
          description: Specifies type of token.
        expires_in:
          type: integer
          description: Specifies the duration of access token expiry.
        refresh_token:
          type: string
          description:  It provides a refresh token, if the access token expires, to get the new access token using the authorization grant.
        scope:
            type: string
            description: Specific actions application can be allowed.
      example:
          access_token: "e3b98877-f225-45e2-add4-3c53eeb6e7a8"
          token_type: "bearer"
          refresh_token: "58f34753-7695-4a71-c08a-d40241ec3dfb"
          expires_in: 4499
          scope: "read write"        